### ISSUE TITLE
Refactor logging code to a separate role

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#102]
Each node creates log directories and configures log directories permissions.

It is a good candidate for the refactoring to a separate role.

https://github.com/poanetwork/deployment-playbooks/blob/master/roles/bootnode/tasks/main.yml#L2-L16

**Comment by ArseniiPetrovich** [comment]
Further investigation showed us, that not only the log creation is common for multiple nodes.
Idea of moving log creation to a separate role was abandoned also.
Instead of, we decided to move all the common tasks to the preconf role.
