### ISSUE TITLE
Refactor AWS-related code

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#104]
To support multiple cloud providers deployment playbooks should clearly separate configuration management code and cloud resources provisioning. 

To achieve this I propose

1. Move AWS-related variables from the `group_vars/all` to a separate file
2. Move AWS firewall configuration from `-access` roles to the `-aws-access` roles
3. Move AWS provisioning code to an `/aws` subfolder

**Comment by ArseniiPetrovich** [comment]
Renaming from -access to -aws-access is not needed since it's already in /aws subfolder
