### ISSUE TITLE
Update SOKOL to parity 1.10

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#107]
**Update instructions**: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

---

#### Things to prepare
- [X] [Playbook](https://github.com/poanetwork/poa-devops/blob/master/roles/upd-parity-version/tasks/main.yml):
    - [X] update fields for bootnodes (https://github.com/poanetwork/deployment-playbooks/pull/105, https://github.com/poanetwork/deployment-playbooks/pull/108)
    - [X] add a check and remove backups from previous updates
    - [X] add support for CentOS updates (for the future)

- [X] Parity binary for orchestrator (https://github.com/phahulin/parity/tree/v1.10.0-disable-parity-whisper-extensions)

- [x] Not sure about `/api/health` endpoint - doesn't work without dapps enabled, maybe re-enable them (https://github.com/paritytech/parity/issues/8245, https://github.com/poanetwork/deployment-playbooks/pull/108)

- [x] Update default version in playbook config (https://github.com/poanetwork/deployment-playbooks/pull/106)

- [X] Launch second MoC node on parity 1.9.2 and CentOS

#### Things to do

- [x] Update nodes (round I):
    - [X] Bootnode
    - [X] Bootnode-Traces
    - [X] Bootnode-CentOS
    - [X] Bootnode-Test-NSG
    - [X] Bootnode-Test
    - [X] Bootnode-Orchestrator-1
    - [X] Bootnode-Orchestrator-2
    - [X] Bootnode-Orchestrator-3
    - [X] Master of Ceremony
    - [ ] ~Master of Ceremony (CentOS)~ (_skips update_)

- [X] Ping Andrew Cravenho to check poa explorer

- [ ] Update nodes (round II):
    - [ ] Jeff Flowers
    - [ ] Jeff Flowers (Val)
    - [x] Jim O'Regan SOKOL Validator Chicago B
    - [ ] John H. LeGassic
    - [ ] Roman Storm

- [ ] Update nodes (round III):
    - [ ] Adam Kagy Sokol Validator
    - [ ] Alex Emelyanov | Sokol
    - [ ] Bootnode Oxana K
    - [ ] Bootnode Sokol Las Vegas A
    - [ ] ~Henry Vishnevsky~ (_skips update_)
    - [ ] Ilmira Nugumanova
    - [ ] ~Jim O'Regan SOKOL Validator Chicago A~ (_skips update_)
    - [ ] John D. Storey
    - [ ] Lillian Chan
    - [ ] Marat Pekker
    - [ ] Melanie Marsollier
    - [ ] Michael Milirud
    - [ ] ~MM Azure EastUS Bootnode~ (_skips update_)
    - [ ] Rocco Federico Mancini
    - [ ] Sherina Hsuan Yang
    - [ ] Sokol Bootnode Toronto A
    - [ ] Sokol Walter Karshat
    - [ ] Stephen Arsenault

- [ ] Check consensus
    - [ ] Add and remove a test validator

- [ ] Update archiving nodes (round IV):
    - [ ] Bootnode-Archive
    - [ ] Bootnode-HB

**Comment by igorbarinov** [comment]
@phahulin what do you think about having different versions of parity on the chain just in case something will go wrong with one version we'll have some nodes on a different version. Ideally will be to have multiple clients, e.g. go-ethereum implementation compatible with AuRa but we don't have it now. What we could do to mitigate the risk is to have multiple versions of the same client at the same time. What do you think?

**Comment by phahulin** [comment]
@igorbarinov I agree.
How do we choose which nodes are upgraded - do we randomly select nodes or let people decide for themselves?

I propose the following:
1. first we do simple tests ourselves to see if new version actually works and check if any updates are required in config files. In the future we can automate more tests ( https://github.com/poanetwork/RFC/issues/11)
2. update playbook accordingly (we'll need to add support for multiple versions in the playbook)
3. notify those operators of sokol nodes who has more technical background to run the upgrade, troubleshoot issues with them
4. if all is well, notify the rest of the sokol network that new version is ready, but leave the decision to perform an upgrade to them. However, we should encourage those who still run too old versions to do the upgrade. Our goal should probably be 2-3 different versions on the network
5. upgraded nodes run on sokol for some time. In the future we can rely on health-checks (https://github.com/poanetwork/RFC/issues/12) to monitor the network during this time.
6. after "quarantine" is over, if no issues were found, we notify operators of core nodes to do the upgrade, but still leave the decision to make an upgrade up to them
7. we don't upgrade all public rpc nodes on core at once

**Comment by 6proof** [comment]
I thought the upgrade path from Parity 1.8.4 to 1.9.2 went well, and what Igor describes seems to follow that pattern.  Identifying at least some nodes to hold in state is a good idea, particularly if option to upgrade is left to rest of the network.  Having a known quantity of baseline nodes may help others feel more comfortable upgrading their nodes.  There is less danger of breaking network when a baseline exists, so less reticence to perform upgrades.  I like and support the staged approach as described.  Looking forward to this next phase!

**Comment by igorbarinov** [comment]
@phahulin we could randomly select three nodes which will not upgrade on Sokol/Core if it's not hard fork

**Comment by 6proof** [comment]
I think at last upgrade for POA Core, DevTeam just designated which nodes stayed on current code, and others upgrade.  That worked will.  This also handles a situation where if, perhaps, a Validator is slow to upgrade their node, one of the reserve nodes can upgrade in that window, and the roles can be exchanged.  I thought the last effort went well, and encourage more, along with Igor's suggestions.  You guys are doing a great job!

**Comment by phahulin** [comment]
@igorbarinov then I suggest we _always_ update MoC, and then select 2 validator nodes and 1 bootnode that will skip the update.
If that's OK, then, for this time, I propose those two validators to be Rocco Mancini and Jim O'Regan (he actually can update one of his two nodes), and the bootnode to be MM Azure EastUS Bootnode

**Comment by 6proof** [comment]
Successfully upgrade Jim O SOKOL Validator Chicago A to Parity version 1.10.0.  Will reserve upgrading Jim O SOKOL Validator Chicago B until directed by POA DevTeam.

**Comment by igorbarinov** [comment]
@phahulin let's have the same setup for MoC (stable+stage version)?

**Comment by phahulin** [comment]
@igorbarinov second instance of MoC is launched, on CentOS

**Comment by phahulin** [comment]
Actually, we shouldn't make a completely random selection of validator nodes to skip the update - it would be better to choose in such a way that the gap between them on validator list is approximately the same. In case of other nodes failure, network would still produce blocks at roughly constant intervals.

That makes it Jim O'Regan (1 of 2 nodes) and Henry Vishnevsky skip the update this time.

**Comment by phahulin** [comment]
This one can be closed now
