### ISSUE TITLE
Unnecesary Environment=MYVAR=myval declaration in templates

### ISSUE THREAD

**Issue by Ykisialiou** [poanetwork/deployment-playbooks#112]
Some templates has unnecessary `Environment=MYVAR=myval` declaration, which should be cleaned up. The list of templates below: 
- roles/netstat/templates/poa-dashboard.j2
- roles/poa-parity/templates/poa-dashboard.j2
- roles/poa-parity/templates/poa-pm2.j2
- roles/poa-pm2/templates/poa-pm2.j2
- roles/explorer/templates/poa-chain-explorer.j2
- roles/poa-parity/templates/poa-chain-explorer.j2
- roles/poa-netstats/templates/poa-netstats.j2
- roles/poa-parity/templates/poa-netstats.j2

**Comment by phahulin** [comment]
Closed via https://github.com/poanetwork/deployment-playbooks/pull/111
