### ISSUE TITLE
Playbook fails on "poa-pm2" role execution

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#124]
Occasionally, while executing "poa-pm2" role playbook fails with the following error:
```
no such file or directory, open '/home/bootnode/.pm2/pm2.log'
```
The workaround for this is:
```
mkdir /home/<role>/.pm2
touch /home/<role>/.pm2/pm2.log
chown <role>:<role> /home/<role>/.pm2 -R
```
where <role> should be replaced with corresponding role name.

The root of this issue, apparently, lies in not sufficient permissions that are granted while executing playbook. This bug will be fixed in the upcoming PR.

**Comment by ArseniiPetrovich** [comment]
#110

**Comment by ArseniiPetrovich** [comment]
The problem is in wrong permissions, that are set for user home folder (`/home/bootnode` for example) while executing user creation directive.
The issue is described at https://github.com/ansible/ansible/issues/24862 and still not solved.
My proposal is to create temporary directive, that will rewrite user home directory permissions recursively:
```
- name: Setup permission
  file: path={{ home }} group={{ username }} owner={{ username }} recurse=yes state=directory
```

**Comment by phahulin** [comment]
Nice workaround, let's do it this way
