### ISSUE TITLE
(Refactor) Limit the use of root

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#125]
At the present moment, it is possible to grant ssh access to `root` user, even though it doesn't seem to be necessary for the playbook to run. Some cloud hostings like amazon or azure by default prevent user from connecting as root.
I suggest to
1. don't explicitly grant ssh access for `root` user
2. where possible, don't run tasks under `root`

**Comment by ArseniiPetrovich** [comment]
Can be closed now due to referenced PRs
