### ISSUE TITLE
Multiple nodes with the same name

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-playbooks#135]
When user provisioning two (or more) nodes of the same type with the same playbooks configuration the `active node count` at netstats dashboard doesn't increase accordingly. The reason for that is in fact, that multiple bootnodes are creating with the same `{{ NODE_FULLNAME }}`. To avoid this i propose to create a condition in jinja template, that will use `{{ NODE_FULLNAME }}` as a node name if there is only one node in a list, or `{{ NODE_FULLNAME }}-{{ counter }}` if there is 2 or more of them.

**Comment by 6proof** [comment]
Hello Arsennii.  Your solution, while elegant, inadvertently removes a network security feature.  There is a distinct advantage to current behavior.  A bootnode or Validator node operator can deploy resilient nodes on diverse networks, significantly increasing network stability without increasing the attack vector or overwhelming the Netstats display page.

Today, a Validator can choose to deploy three nodes in three different data centers on three different networks, protecting against all manner of disaster and outage while publicly displaying only a single node instance, allowing an independent Validator or bootnode operator to increase the reliability of their node(s).  Any node operator wanting to run publicly identifiable diverse nodes may manually name their nodes in the fashion you have described.

Please consider these thoughts before changing current behavior.  If there is a technical reason that current behavior must change, please consider a method that will allow the options presented herein.  Thank you for all of your efforts, and keep up the good work!

**Comment by phahulin** [comment]
Hello, Jim @6proof 
Thank you for keeping an eye on this repository! We greatly appreciate it.

This feature is mostly for our future work on terraform, where we'll need to create multiple nodes of the same type for bootstrapping test networks, so we'd like to use `counter` variable to run playbook once and create required amount of nodes in one go.
After this solution is implemented, you will still have an ability to create multiple nodes with the same name in different regions, but spawning them one-by-one and setting required `NODE_FULLNAME`.
What do you think?

**Comment by ArseniiPetrovich** [comment]
There are also might be a compromise solution. I'm not sure about if I will not encounter some obstacles, but idea is to rewrite `NODE_FULLNAME` to be an array instead of simple string. If it has only one element - it will be assigned to all the nodes of the same type. Otherway - different names will be assigned. It also will give user a bit more flexibility to setup names whatever he likes.

**Comment by 6proof** [comment]
Hello phahulin, thank you for the details.  Yes, this looks fine, as we can still deploy nodes as outline.  Arsenni, your original proposal looks good - very nice!

**Comment by ArseniiPetrovich** [comment]
This feature is implemented at https://github.com/poanetwork/deployment-terraform/pull/26 and is not considered in the scope of this repo anymore.
