### ISSUE TITLE
Is MoC already hardcoded into spec.json?

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/deployment-playbooks#142]
Is there a way to specify a different spec.json? 
I think our playbook is using poa-chain-spec which already has MoC address built in

**Comment by phahulin** [comment]
NB: When launching new networks based make sure to checkout either `sokol` or `core` branch. `master` is currently being updated, something might be broken

There is no built-in way to do it, however there are some workarounds that depend on what exactly you want to achieve.
1. if you plan on changing other things, you can fork all related repositories ([deployment-playbooks](https://github.com/poanetwork/deployment-playbooks), [poa-scripts-validator](https://github.com/poanetwork/poa-scripts-validator), [poa-scripts-moc](https://github.com/poanetwork/poa-scripts-moc), [poa-chain-spec](https://github.com/poanetwork/poa-chain-spec), [eth-netstats](https://github.com/poanetwork/eth-netstats), [eth-net-intelligence-api](https://github.com/poanetwork/eth-net-intelligence-api), [chain-explorer](https://github.com/poanetwork/chain-explorer)) to your account `rstormsf` and then change this variable https://github.com/poanetwork/deployment-playbooks/blob/sokol/group_vars/all.network#L32 to `rstormsf`

2. if you just want to change spec file, you'll need to provide its url here:
https://github.com/poanetwork/deployment-playbooks/blob/sokol/roles/bootnode/tasks/main.yml#L18
https://github.com/poanetwork/deployment-playbooks/blob/sokol/roles/explorer/tasks/main.yml#L18
https://github.com/poanetwork/deployment-playbooks/blob/sokol/roles/moc/tasks/main.yml#L18
https://github.com/poanetwork/deployment-playbooks/blob/sokol/roles/validator/tasks/main.yml#L18
