### ISSUE TITLE
vpc_id not specified for sg configuration

### ISSUE THREAD

**Issue by Ykisialiou** [poanetwork/deployment-playbooks#143]
If several VPC exist, the security groups are cre created in default one. This should be an option. 
As terraform installer is under construction, it's not something for immidiate fix, but a bug, that should be checked in terraform installer.

**Comment by ArseniiPetrovich** [comment]
As for https://github.com/poanetwork/deployment-terraform/pull/26 terraform creates unique VPC for each deployed network to avoid any possible conflicts with other deployments.
