### ISSUE TITLE
(Sokol) Update SOKOL to 1.11.8

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#156]
### Playbook
https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

### 1. Nodes to be updated

* **Bootnodes**:
- [x] Alex Beal Sokol Bootnode
- [x] Artiom C Bootnode
- [X] Bootnode
- [ ] Bootnode - Suzon Crowell
- [ ] Bootnode NStoyev
- [x] Bootnode Sokol Las Vegas A
- [x] Bootnode Theresa Cable
- [X] Bootnode-2
- [X] Bootnode-3
- [ ] Bootnode-Archive
- [X] Bootnode-Azure-1
- [X] Bootnode-Azure-2
- [X] Bootnode-Azure-3
- [X] Bootnode-CentOS
- [ ] Bootnode-HB
- [ ] Bootnode-Orchestrator-1
- [ ] Bootnode-Orchestrator-2
- [ ] Bootnode-Orchestrator-3
- [X] Bootnode-OVH
- [X] Bootnode-Test
- [X] Bootnode-Test-NDP
- [X] Bootnode-Test-NSG
- [X] Bootnode-Traces
- [X] Bootnode-Traces-2
- [X] Bootnode-Traces-3
- [X] Bootnode-Traces-4
- [X] Bootnode-Traces-5
- [X] Bootnode-Traces-6
- [X] Bootnode-WS
- [X] Explorer
- [ ] Irvin Cardenas Bootnode
- [x] James McGrath Sokol Bootnode
- [x] Jeff Flowers
- [ ] Kevin Joy Sokol Bootnode
- [x] MM Azure EastUS Bootnode
- [x] Monitoring
- [x] Sokol Bootnode Toronto A

* **Validators**:
- [x] Adam Kagy Sokol Validator
- [x] Alex Emelyanov | Sokol
- [x] Artiom Curencov
- [x] Henry Vishnevsky
- [x] Ian Ferrell Validator
- [x] Ilmira Nugumanova
- [x] James McGrath Sokol Validator
- [x] Jeff Flowers (Val)
- [x] Jim O'Regan SOKOL Validator Chicago A
- [x] Jim O'Regan SOKOL Validator Chicago B
- [x] John D. Storey
- [x] John H. LeGassic
- [x] Kristina Yevseyeva Sokol
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets | NYC-v2
- [x] Peter Chen Sokol Validator
- [x] Rocco Federico Mancini
- [X] Roman Storm
- [x] Sherina Hsuan Yang
- [x] Sokol Walter Karshat
- [x] Stephen Arsenault
- [x] Validator Theresa Cable

* **Master of Ceremony**
- [X] Master of Ceremony
- [X] Master of Ceremony (CentOS)

### 2. Notify
- [X] POA Explorer team & Andrew

### 3. Checks
- [x] Monitoring
- [X] MEW

### 4. Things to do
- [x] Update deployment-playbooks (https://github.com/poanetwork/deployment-playbooks/pull/158)

**Comment by ajkagy** [comment]
"Bootnode Sokol Las Vegas A"
"Adam Kagy Sokol Validator"

These nodes have been updated.

**Comment by JamesWMcGrath** [comment]
Bootnode "James McGrath Sokol Bootnode" and Validator Node "James McGrath Sokol Validator" are updated.

**Comment by shkron** [comment]
Validator node "Alex Emelyanov | Sokol" updated.

**Comment by 6proof** [comment]
Sokol Validator nodes "Jim O'Regan SOKOL Validator Chicago A" and "Jim O'Regan SOKOL Validator Chicago B" are updated to 1.11.8 - will keep an eye on payout key and netstats activity over next 24 hours. Good work DevTeam!

**Comment by henryvishnevsky** [comment]
Validator node "Henry Vishnevsky" updated to Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2

**Comment by mnugumanova** [comment]
Validator node " Ilmira Nugumanova" is updated

**Comment by alexanderjbeal** [comment]
"Alex Beal Sokol Bootnode" is updated - Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2

**Comment by intersectional** [comment]
"Peter Chen Sokol Validator" has been updated to Parity//v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2

**Comment by micwebnet** [comment]
Updated both boot and validator Sokol nodes.

**Comment by phahulin** [comment]
Done
