### ISSUE TITLE
(Core) Update CORE to 1.11.8

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#157]
### Playbook
https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

### 1. Nodes to be updated

* **Bootnodes**

- [x] Bootnode A
- [x] Bootnode Adam Kagy
- [x] Bootnode Atlanta A
- [x] Bootnode Azure Brazil A
- [x] Bootnode B
- [x] Bootnode C
- [x] Bootnode Chicago A
- [x] Bootnode Chicago B
- [x] Bootnode Chicago C
- [x] Bootnode Chicago D
- [x] Bootnode D
- [x] Bootnode Dallas A
- [ ] Bootnode Frankfurt
- [x] Bootnode MoC OVH
- [x] Bootnode MoC OVH-2
- [ ] Bootnode NStoyev
- [x] Bootnode Santa Clara
- [ ] Bootnode-Archive
- [x] Bootnode-Azure-1
- [x] Bootnode-Azure-2
- [x] Bootnode-Azure-3
- [x] Bootnode-Core-B
- [x] Bootnode-E
- [x] Bootnode-F
- [x] Bootnode-G
- [x] Bootnode-H
- [ ] Bootnode-HB
- [x] Bootnode-Traces
- [x] Bootnode-WS
- [x] Explorer
- [x] Monitoring
- [x] Sviataslau Vishneuski Bootnode

* **Validators**
- [x] Adam Kagy
- [x] Alex Emelyanov
- [x] Ilmira Nugumanova
- [x] James McGrath
- [x] Jeff Flowers
- [x] Jim O'Regan
- [x] John D. Storey
- [x] John H LeGassic
- [x] Kristina Yevseyeva Core
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets
- [x] Rocco Federico Mancini
- [x] Sherina Hsuan Yang
- [x] Stephen Arsenault
- [x] Sviataslau Vishneuski
- [x] Walter Karshat
- [x] Xiaobo (Peter) Chen

* **Master of Ceremony**
- [x] Master of Ceremony

### 2. Notify
- [x] POA Explorer team & Andrew
- [ ] Infura
- [ ] Binance
- [ ] ??

### 3. Checks
- [ ] Monitoring
- [ ] MEW

### 4. Things to do
- [ ] Update deployment-playbooks

**Comment by 6proof** [comment]
Bootnodes Chicago A, B C and D plus Jim O'Regan Validator nodes all successfully updated to 1.11.8 on POA Core

**Comment by 6proof** [comment]
Xiaobo (Peter) Chen Validator node update to 1.11.8 on POA Core.

**Comment by 6proof** [comment]
Oxana Kunets Validator node updated to 1.11.8 o POA Core.

**Comment by ajkagy** [comment]
"Bootnode Adam Kagy" and "Adam Kagy" have been updated.

**Comment by wkarshat** [comment]
Walter Karshat updated to Parity 1.11.8 on Core

**Comment by JamesWMcGrath** [comment]
"James McGrath" updated to 1.11.8

**Comment by shkron** [comment]
Alex Emelyanov Core Validator updated to Parity 1.11.8

**Comment by henryvishnevsky** [comment]
Sviataslau Vishneuski's bootnode and validator node are updated.

**Comment by micwebnet** [comment]
Michael Milirud Core validator node upgraded without issues.

**Comment by Mel-Marsollier** [comment]
Melanie Marsollier's Core validator updated.

**Comment by phahulin** [comment]
Done
