### ISSUE TITLE
`npm` ansible module sometimes doesn't work

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#162]
As an example - it doesn't look like this line is executed
https://github.com/poanetwork/deployment-playbooks/blob/master/roles/validator/tasks/main.yml#L32

**Comment by ArseniiPetrovich** [comment]
I can refer https://github.com/ansible/ansible/issues/29192 and https://github.com/ansible/ansible/issues/29240 here.
As we can see at referenced links those errors are "heisenbugs". I suppose it would be a good idea for now to replace `npm` ansible module with a `shell` doing the same stuff.

**Comment by phahulin** [comment]
BTW, netstats restart this is not required there
https://github.com/poanetwork/deployment-playbooks/blob/master/roles/validator/tasks/main.yml#L38

**Comment by phahulin** [comment]
Closed via #164
