### ISSUE TITLE
node config: min_peers and max_peers belong to network section

### ISSUE THREAD

**Issue by d10r** [poanetwork/deployment-playbooks#174]
The node template config has parameters `min_peer` and `max_peers` in section `footprint` (see e.g. [here](
https://github.com/poanetwork/deployment-playbooks/blob/d93fecb7d0a60dd77a4a1c0c6ad3941b6cc8328a/roles/validator/templates/node.toml.j2#L48)).  
[According to the doc](https://wiki.parity.io/Configuring-Parity-Ethereum) those belong to the `network` section instead.

**Comment by phahulin** [comment]
This is fixed in PRs above, thanks for the report!
