### ISSUE TITLE
node config broken when using domain names in inventory

### ISSUE THREAD

**Issue by d10r** [poanetwork/deployment-playbooks#175]
The node config templates contain param `nat` for explicit assignment of the IP - which is used by Parity for constructing the enode.  
This is useful for hosts behind a NAT (with forwarded port) or with multiple network interfaces.  
However this parameters works only if an IP address is assigned. If it's a domain name, Parity can't parse it.  

As is set now (using `{{ ansible_host }}`), a domain name will be assigned if that's what's in the used inventory file, leading to a broken config.  

Possible solutions:
* Use `{{ ansible_default_ipv4.address }}` instead. I'm not sure what exactly that does, it may also be a non-solution - in the sense that we end up with the setting which would have been chosen anyway were this parameter not present at all.
* Omit parameter `nat` by default and set it only if an IP was explicitly defined via ENV variable.

**Comment by ArseniiPetrovich** [comment]
@phahulin Could you clarify one thing for me, please? Do we need `nat="extip:{{ ansible_host }}"` public or private IP here? Ansible has modules that can be used to retrieve target machine public IP.

**Comment by phahulin** [comment]
We need public ip there

**Comment by ArseniiPetrovich** [comment]
Thanks. I'll prepare a PR to fix this.
