### ISSUE TITLE
(master, dai) open ssl error when installing bootnode

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#195]
When creating bootnode via ansible playbook, then following error appears:

```
TASK [nginx : Generate SSL private key] ******************************************
fatal: [1.1.1.1]: FAILED! => {"changed": false, "msg": "the python pyOpenSSL module is required"}
```
I have ansible 2.6.3

It seems like pyOpenSSL is actually installed on the remote, so it's not clear why this error happens
```
$ pip3 show pyOpenSSL
---
Metadata-Version: 2.1
Name: pyOpenSSL
Version: 18.0.0
Summary: Python wrapper module around the OpenSSL library
...
```

**Comment by ArseniiPetrovich** [comment]
Hi, @phahulin. Can you confirm that `ansible_python_interpreter` is set to `python3`?
Also, what is the OS you are using?

**Comment by phahulin** [comment]
`ansible_python_interpreter` is set to `python3` in `aws/group_vars/all.yml`, but not in `group_vars/all.yml`

I'm using Ubuntu 16.04

**Comment by ArseniiPetrovich** [comment]
> `ansible_python_interpreter` is set to `python3` in `aws/group_vars/all.yml`, but not in `group_vars/all.yml`

And what about `group_vars/ubuntu` file?

**Comment by phahulin** [comment]
It's set to `ansible_python_interpreter: /usr/bin/python3`

**Comment by ArseniiPetrovich** [comment]
I can confirm that issue persist. However I'm not sure what is the root for this, but `ansible_python_interpreter` is set to `python2` somehow. As a temporary workaround use -e "ansible_python_interpreter=/usr/bin/python3", please. Will be fixed soon.

**Comment by phahulin** [comment]
Can't reproduce anymore
