### ISSUE TITLE
(Sokol) Update parity to 2.2.5 and Constantinople

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#203]
### Playbook
* Constantinople HF: https://github.com/poanetwork/wiki/wiki/HFs-Sokol-2019-01-04
* New parity version: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md with `GENESIS_BRANCH: "sokol"`

### 1. Nodes to be updated

* **Bootnodes**:
- [ ] ~Artiom C Bootnode~
- [ ] Bootnode NStoyev
- [x] Bootnode Sokol Las Vegas A
- [x] Bootnode-ASG-Main
- [x] Bootnode-Azure-1
- [x] Bootnode-OVH
- [x] Bootnode-Traces
- [ ] Dzmitry Miranovich, Sokol Node
- [ ] James McGrath Sokol Bootnode
- [x] Jeff Flowers
- [x] MM Azure EastUS Bootnode
- [x] Monitoring
- [ ] Siarhei Barylau bootnode
- [x] Sokol Bootnode Toronto A

* **Validators**:
- [x] Adam Kagy Sokol Validator
- [x] Alex Emelyanov | Sokol
- [x] Artiom Curencov
- [x] Henry Vishnevsky
- [x] Ian Ferrell Validator
- [x] Ilmira Nugumanova
- [x] Irvin Cardenas Validator
- [ ] James McGrath Sokol Validator
- [x] Jeff Flowers (Val)
- [x] Jim O'Regan SOKOL Validator Chicago A
- [x] Jim O'Regan SOKOL Validator Chicago B
- [x] John D. Storey
- [x] John H. LeGassic
- [x] Kristina Yevseyeva Sokol
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets | NYC-v2
- [x] Peter Chen Sokol Validator
- [x] Rocco Federico Mancini
- [x] Roman Storm
- [x] Sherina Hsuan Yang
- [x] Sokol Walter Karshat
- [x] Stephen Arsenault

* **Master of Ceremony**
- [x] Master of Ceremony

Explorers:
- [x] Explorer
- [x] Blockscout tracing node

### 2. Notify
- [x] POA Explorer team & Andrew

### 3. Checks
- [x] Monitoring
- [x] MEW

### 4. Things to do
- [X] Playbook update (default parity version) https://github.com/poanetwork/deployment-playbooks/pull/198

**Comment by kPatch** [comment]
Irvin Cardenas Validator node has been updated and verified.

**Comment by elillian** [comment]
Lillian Chan validator node has been updated and verified.

**Comment by jflowers1974** [comment]
Done

**Comment by ajkagy** [comment]
"Bootnode Sokol Las Vegas A" and "Adam Kagy Sokol Validator" have been updated and verified.

**Comment by shkron** [comment]
"Alex Emelyanov | Sokol" updated

**Comment by 6proof** [comment]
Jim O'Regan Sokol Validator Chicago A and Chicago B update and verified.

**Comment by mnugumanova** [comment]
Ilmira Nugumanova validator node has been updated

**Comment by henryvishnevsky** [comment]
"Henry Vishnevsky" Validator node updated and verified.

**Comment by phahulin** [comment]
Done
