### ISSUE TITLE
(Core) Update parity to 2.2.1

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#204]
1. Playbook: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md with `GENESIS_BRANCH: "core"`
**make sure to do git pull before upgrading, and read the instruction**

2. Nodes to be upgraded

Bootnodes:
- [x] Bootnode Atlanta A
- [x] Bootnode Azure Brazil A
- [x] Bootnode Chicago A
- [x] Bootnode Chicago C
- [x] Bootnode Chicago D
- [x] Bootnode Dallas A
- [ ] Bootnode Frankfurt
- [X] Bootnode MoC OVH
- [X] Bootnode MoC OVH-2
- [ ] Bootnode NStoyev
- [x] Bootnode Santa Clara
- [x] Bootnode-ASG-main
- [x] Bootnode-Azure-1
- [x] Bootnode-Discovery
- [x] Bootnode-Traces
- [x] Monitoring
- [x] Sviataslau Vishneuski Bootnode

Validators:
- [x] Adam Kagy
- [x] Alex Emelyanov
- [x] Artiom Curencov
- [x] Ian Ferrell
- [x] Ilmira Nugumanova
- [ ] James McGrath
- [x] Jeff Flowers
- [x] Jim O'Regan
- [x] John D. Storey
- [x] John H LeGassic
- [x] Kristina Yevseyeva Core
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets
- [x] Rocco Federico Mancini
- [x] Sherina Hsuan Yang
- [x] Stephen Arsenault
- [x] Sviataslau Vishneuski
- [x] Walter Karshat
- [x] Xiaobo (Peter) Chen

Master of Ceremony:
- [X] Master of Ceremony

Explorers:
- [X] Explorer
- [X] Blockscout's archive node

3. Default parity version: https://github.com/poanetwork/deployment-playbooks/pull/202

**Comment by jflowers1974** [comment]
Done

**Comment by shkron** [comment]
"Alex Emelyanov" validator node has been updated

**Comment by henryvishnevsky** [comment]
"Sviataslau Vishneuski" bootnode and validator node updated.

**Comment by hashguide** [comment]
Validator `Stephen Arsenault` and bootnodes `Bootnode Atlanta A` `Bootnode Dallas A` all updated.

**Comment by 6proof** [comment]
Bootnodes Chicago A, C and D all updated.
Jim O'Regan Validator Node updated.

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node has been updated

**Comment by phahulin** [comment]
Done
