### ISSUE TITLE
(Core) Update to parity 2.2.5 and Constantinople

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#211]
1. ~Instructions:
    https://github.com/poanetwork/wiki/wiki/HFs-Core-2019-01-18~
Constantinople is postponed, to rever changes please follow these stetps:

* https://github.com/poanetwork/poa-devops/blob/master/docs/Spec-hardfork.md

* on STEP 2 (create group_vars/all...) use the following parameters:
```
MAIN_REPO_FETCH: "poanetwork"
GENESIS_BRANCH: "core"
```
* on STEP 3 (create/edit hosts file...) please double-check that you're using your CORE node's IP address
* on STEP 6 (connect to the node...) after you've done all the checks, also verify HF block number:
```
cd /home/validator  #or /home/bootnode
grep -n -A2 6843780 spec.json
```
output should be empty, it means that HF transition parameters were successfully removed.

-------

2. Nodes to be upgraded:

* Bootnodes:
- [x] :heavy_check_mark: Bootnode Atlanta A
- [x]  :heavy_check_mark: Bootnode Chicago A
- [x]  :heavy_check_mark: Bootnode Chicago C
- [x]  :heavy_check_mark: Bootnode Chicago D
- [x] :heavy_check_mark: Bootnode Dallas A
- [ ] Bootnode Frankfurt
- [ ] Bootnode NStoyev
- [X] :heavy_check_mark: Bootnode Santa Clara
- [X] :heavy_check_mark: Bootnode-ASG-main
- [X] :heavy_check_mark: Bootnode-Azure-1
- [X] :heavy_check_mark: Bootnode-Discovery
- [x] :heavy_check_mark: Monitoring
- [ ] ~Sviataslau Vishneuski Bootnode~

* Validators:
- [x] :heavy_check_mark: Adam Kagy
- [x] :heavy_check_mark: Alex Emelyanov
- [x] :heavy_check_mark: Artiom Curencov
- [x] :heavy_check_mark: Ian Ferrell
- [x]  :heavy_check_mark: Ilmira Nugumanova
- [ ] ~James McGrath~
- [x] :heavy_check_mark: Jeff Flowers
- [x]  :heavy_check_mark: Jim O'Regan
- [x] :heavy_check_mark: John D. Storey
- [x] :heavy_check_mark: John H LeGassic
- [x] :heavy_check_mark: Kristina Yevseyeva Core
- [x] :heavy_check_mark: Lillian Chan
- [x] :heavy_check_mark: Marat Pekker
- [x] :heavy_check_mark: Melanie Marsollier
- [x] :heavy_check_mark: Michael Milirud
- [ ]  :heavy_check_mark: Oxana Kunets
- [x] :heavy_check_mark: Rocco Federico Mancini
- [x] :heavy_check_mark: Sherina Hsuan Yang
- [x] :heavy_check_mark: Stephen Arsenault
- [x] :heavy_check_mark: Sviataslau Vishneuski
- [x] :heavy_check_mark: Walter Karshat
- [x] :heavy_check_mark: Xiaobo (Peter) Chen

* Master of Ceremony:
- [X] :heavy_check_mark:  Master of Ceremony

* Explorers:
- [x] :heavy_check_mark: Explorer
- [x] :heavy_check_mark: Blockscout's archive node

3. Exchanges:
- [x]  :heavy_check_mark: Binance
- [ ] BiBox

4. Other
- [x] :heavy_check_mark: Infura
- [ ] Coinomy

4. PR ot update default parity version: TBA

**Comment by ajkagy** [comment]
"Adam Kagy" node has been updated.

**Comment by jflowers1974** [comment]
Done as well

**Comment by RoccoFMancini** [comment]
Done

**Comment by shkron** [comment]
"Alex Emelyanov" updated

**Comment by berry88** [comment]
Updated.

**Comment by 6proof** [comment]
Bootnodes Chicago A, C and D, Jim O'Regan Validator node updated and verified.  Great work POA DevTeam!

**Comment by hashguide** [comment]
[x] Stephen Arsenault
[x] Bootnode Atlanta A
[x] Bootnode Dallas A

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node has been updated

**Comment by Mel-Marsollier** [comment]
Melanie Marsollier Core updated.

**Comment by elillian** [comment]
Lillian Chan Core has been updated

**Comment by 6proof** [comment]
Due to discovered Constantinople EIP vulnerability and in conjunction with POA DevTeam updates, reverted hard fork and confirmed for Bootnode Chicago A, C, D and Jim O'Regan Validator Nodes.

**Comment by ajkagy** [comment]
Reverted spec for "Adam Kagy"

**Comment by Mel-Marsollier** [comment]
Reverted spec for Melanie Marsollier and verified.

**Comment by johnnynuuma** [comment]
spec.json reverted and verified on core

**Comment by RoccoFMancini** [comment]
Reverted and verified for Rocco Mancini

**Comment by micwebnet** [comment]
spec.json reverted and verified using playbook for Michael Milirud core validator node.

**Comment by henryvishnevsky** [comment]
Reverted and verified for Sviataslau Vishneuski

**Comment by berry88** [comment]
Kristina Yevseyeva Core reverted successfully.

**Comment by hashguide** [comment]
- [x] Stephen Arsenault
- [x] Bootnode Atlanta A
- [x] Bootnode Dallas A

reverted and verified

**Comment by shkron** [comment]
Reverted and verified for Alex Emelyanov

**Comment by phahulin** [comment]
"Done"
