### ISSUE TITLE
(Core) update to parity 2.3.0

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#212]
1. Instructions
https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

-------

2. Nodes to be upgraded:

* Bootnodes:
- [x] Bootnode Atlanta A
- [X] Bootnode Chicago A
- [X] Bootnode Chicago C
- [X] Bootnode Chicago D
- [x] Bootnode Dallas A
- [ ] Bootnode Frankfurt
- [ ] Bootnode NStoyev
- [x] Bootnode Santa Clara
- [X] Bootnode-ASG-main
- [X] Bootnode-Azure-1
- [X] Bootnode-Discovery
- [X] Monitoring

* Validators:
- [x] Adam Kagy
- [x] Alex Emelyanov
- [x] Artiom Curencov
- [x] Ian Ferrell
- [x] Ilmira Nugumanova
- [x] Jeff Flowers
- [x] Jim O'Regan
- [x] John D. Storey
- [x] John H LeGassic
- [x] Kristina Yevseyeva Core
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets
- [x] Rocco Federico Mancini
- [x] Sherina Hsuan Yang
- [x] Stephen Arsenault
- [x] Sviataslau Vishneuski
- [x] Walter Karshat
- [x] Xiaobo (Peter) Chen

* Master of Ceremony:
- [X]  Master of Ceremony

* Explorers:
- [X] Explorer
- [X] Blockscout's archive node

* Exchanges:
- [x] Binance
- [ ] BiBox

* Other
- [x] Infura
- [ ] Coinomy

3. - [X] PR ot update default parity version: https://github.com/poanetwork/deployment-playbooks/pull/213

**Comment by ajkagy** [comment]
"Adam Kagy" updated.

**Comment by hashguide** [comment]
- [x] Stephen Arsenault
- [x] Bootnode Atlanta A
- [x] Bootnode Dallas A

All updated and verified.

**Comment by henryvishnevsky** [comment]
"Sviataslau Vishneuski" validator node updated

**Comment by elillian** [comment]
updated and verified

**Comment by johnnynuuma** [comment]
updated and verified core validator node 
	
Parity-Ethereum//v2.3.0-beta-10657d9-20190115/x86_64-linux-gnu/rustc1.31.1

**Comment by 6proof** [comment]
Jim O'Regan POA Core Validator node updated to Parity Version 2.3.0-beta and verified, along with Bootnodes Chicago A, C and D earlier (already noted above).

**Comment by Mel-Marsollier** [comment]
Melanie Marsollier updated and verified

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node has been updated and verified.

**Comment by phahulin** [comment]
Done
