### ISSUE TITLE
(Sokol) update to 2.3.1/2.3.2 and disable EIP1283 HF

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#215]
### Playbook
* New parity version: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md with `GENESIS_BRANCH: "sokol"`
* Disable EIP 1283: https://github.com/poanetwork/wiki/wiki/HFs-Sokol-2019-02-06

### 1. Nodes to be updated

* **Bootnodes**:
- [ ] Bootnode NStoyev
- [x] Bootnode Sokol Las Vegas A
- [X] Bootnode-ASG-Main
- [X] Bootnode-Azure-1
- [x] Jeff Flowers
- [x] MM Azure EastUS Bootnode
- [x] Monitoring
- [x] Sokol Bootnode Toronto A

* **Validators**:
- [x] Adam Kagy Sokol Validator
- [x] Alex Emelyanov | Sokol
- [x] Artiom Curencov
- [x] Henry Vishnevsky
- [x] Ian Ferrell Validator
- [x] Ilmira Nugumanova
- [x] Irvin Cardenas Validator
- [x] Jeff Flowers (Val)
- [x] Jim O'Regan SOKOL Validator Chicago A
- [x] Jim O'Regan SOKOL Validator Chicago B
- [x] John D. Storey
- [x] John H. LeGassic
- [x] Kristina Yevseyeva Sokol
- [x] Lillian Chan
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets | NYC-v2
- [x] Peter Chen Sokol Validator
- [x] Rocco Federico Mancini
- [x] Roman Storm
- [x] Sherina Hsuan Yang
- [x] Sokol Walter Karshat
- [x] Stephen Arsenault

* **Master of Ceremony**
- [X] Master of Ceremony

Explorers:
- [x] Explorer
- [x] Blockscout tracing node

### 2. Notify
- [ ] POA Explorer team & Andrew

### 3. Checks
- [x] Monitoring
- [x] MEW

### 4. Things to do
- [x] Playbook update (default parity version) https://github.com/poanetwork/deployment-playbooks/pull/216

**Comment by berry88** [comment]
Updated.

**Comment by henryvishnevsky** [comment]
"Henry Vishnevsky" validator node updated to parity 2.3.2 and disabled EIP1283 HF.

**Comment by johnnynuuma** [comment]
sokol node updated to parity v2.3.2 and hard fork spec change applied & verified

**Comment by hashguide** [comment]
- [x] Stephen Arsenault
- [x] Sokol Bootnode Toronto A

Parity and Spec.json updated and verified.

**Comment by elillian** [comment]
Parity and spec.json updated and verified

**Comment by micwebnet** [comment]
Boot and validator nodes updated to 2.3.2 and new hf spec.

**Comment by kPatch** [comment]
Updated and verified to 2.3.2

**Comment by phahulin** [comment]
Done
