### ISSUE TITLE
(Core) Constantinople/St.Petersfork HF and parity 2.3.2

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#219]
Date: 2019-04-29
Block number: 8582254

1. Upgrade instructions:
    - [x] https://github.com/poanetwork/wiki/wiki/HFs-Core-2019-04-29

2. Chain spec update:
    - [x] https://github.com/poanetwork/poa-chain-spec/pull/110

3. Nodes to be upgraded:

* Bootnodes:
    - [x] Bootnode Atlanta A
    - [x] Bootnode Dallas A
    - [x] Bootnode Chicago A
    - [x] Bootnode Chicago D
    - [ ] Bootnode Frankfurt
    - [x] Bootnode Santa Clara
    - [x] Bootnode-ASG-main
    - [x] Bootnode-Azure-1
    - [x] Bootnode-Discovery
    - [x] Monitoring

* Validators:
    - [x] Adam Kagy
    - [x] Alex Emelyanov
    - [x] Artiom Curencov
    - [x] Ian Ferrell
    - [x] Ilmira Nugumanova
    - [x] Irvin Cardenas
    - [x] Jeff Flowers
    - [x] Jim O'Regan
    - [x] John D. Storey
    - [x] John H LeGassic
    - [x] Kristina Yevseyeva Core
    - [x] Lillian Chan
    - [x] Marat Pekker
    - [x] Melanie Marsollier
    - [x] Michael Milirud
    - [x] Oxana Kunets
    - [x] Sherina Hsuan Yang
    - [x] Stephen Arsenault
    - [x] Sviataslau Vishneuski
    - [x] Xiaobo (Peter) Chen

* Master of Ceremony:
    - [x]  Master of Ceremony

* Explorers:
    - [x] "Old" Explorer
    - [x] Blockscout's archive node

4. Exchanges:
   - [x] Binance
   - [x] BiBox

5. Other
    - [ ] Coinomy

6. Update default parity version in playbooks:
    - [x] https://github.com/poanetwork/deployment-playbooks/pull/220

7. PR to parity upstream
   - [x] https://github.com/paritytech/parity-ethereum/pull/10606

**Comment by 6proof** [comment]
Updated and verified Bootnodes Chicago A, Chicago D and Jim O'Regan Validator nodes.

**Comment by ajkagy** [comment]
node "Adam Kagy" updated and verified.

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node has been updated

**Comment by johnnynuuma** [comment]
JLeGassic node has been updated & verified

**Comment by henryvishnevsky** [comment]
Sviataslau Vishneuski validator node has been updated & verified

**Comment by phahulin** [comment]
Done
