### ISSUE TITLE
Remove Chain Archive after download

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/deployment-playbooks#224]
https://github.com/poanetwork/deployment-playbooks/blob/kovan/download-kovan.sh

I think it should remove tar file after it unpacked it

@phahulin 

I don't think we want extra 30gb hanging around

**Comment by phahulin** [comment]
Added a check that parity service is running, if it does archive is removed
https://github.com/poanetwork/deployment-playbooks/blob/8001dffb8e674c0c8a7d41bc3d28a10da2fca7e1/download-kovan.sh#L47-L52
