### ISSUE TITLE
(Sokol) Update to parity 2.4.6

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#225]
### Playbook
* New parity version: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md with `GENESIS_BRANCH: "sokol"`

### 1. Nodes to be updated

* **Bootnodes**:
- [x] Bootnode Sokol Las Vegas A
- [x] Bootnode-ASG-*
- [x] Bootnode-Azure-1
- [x] Kiryl Ihnatsyeu Bootnode
- [x] MM Azure EastUS Bootnode
- [x] Monitoring
- [x] Sokol Bootnode Toronto A

* **Validators**:
- [x] Adam Kagy Sokol Validator
- [x] Alex Emelyanov | Sokol
- [x] Artiom Curencov
- [x] Henry Vishnevsky
- [x] Ian Ferrell Validator
- [x] Ilmira Nugumanova
- [x] Irvin Cardenas Validator
- [x] Jim O'Regan SOKOL Validator Chicago A
- [x] Jim O'Regan SOKOL Validator Chicago B
- [x] John D. Storey
- [x] John H. LeGassic
- [x] Kristina Yevseyeva Sokol
- [x] Kiryl Ihnatsyeu
- [x] Marat Pekker
- [x] Melanie Marsollier
- [x] Michael Milirud
- [x] Oxana Kunets | NYC-v2
- [x] Peter Chen Sokol Validator
- [x] Sherina Hsuan Yang
- [x] Stephen Arsenault

* **Master of Ceremony**
- [x] Master of Ceremony

Explorers:
- [x] "Old" Explorer
- [x] Blockscout tracing node

### 2. Notify
- [x] Blockscout

### 3. Checks
- [x] Monitoring
- [X] MEW
- [x] Resync

### 4. Things to do
- [x] Playbook update (default parity version) https://github.com/poanetwork/deployment-playbooks/pull/226

**Comment by johnnynuuma** [comment]
John H. LeGassic -- sokol node upgraded and verified

**Comment by shkron** [comment]
Alex Emelyanov node upgraded

**Comment by 6proof** [comment]
Jim O'Regan SOKOL Validator Chicago A and B nodes upgraded and verfied.

**Comment by henryvishnevsky** [comment]
Henry Vishnevsky node upgraded

**Comment by ajkagy** [comment]
"Adam Kagy Sokol Validator" and "Bootnode Sokol Las Vegas A" upgraded.

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node's been updated

**Comment by hashguide** [comment]
"Stephen Arsenault" and "Sokol Bootnode Toronto A" updated.

**Comment by micwebnet** [comment]
Validator and bootnode updated.

**Comment by intersectional** [comment]
Peter Chen Sokol Validator updated and verified.

**Comment by Mel-Marsollier** [comment]
Melanie Sokol Validator Updated

**Comment by phahulin** [comment]
Done
