### ISSUE TITLE
Potential Issue:  sokol branch group_vars/all.example - *_BRANCH tokens point to master

### ISSUE THREAD

**Issue by johnnynuuma** [poanetwork/deployment-playbooks#32]
Is this OK?

jhl@johnny-lenovo:~/poa-network/deployment-playbooks/group_vars$ git branch
* sokol
jhl@johnny-lenovo:~/poa-network/deployment-playbooks/group_vars$ grep -n BRANCH * | grep -v sokol
all.example:34:TEMPLATES_BRANCH: "dev-mainnet"
all.example:35:GENESIS_BRANCH: "master"
all.example:42:SCRIPTS_MOC_BRANCH: "master"
all.example:43:SCRIPTS_VALIDATOR_BRANCH: "master"
jhl@johnny-lenovo:~/poa-network/deployment-playbooks/group_vars$

**Comment by phahulin** [comment]
This is OK, but I added a warning on top of `group_vars/all.example` that this file is used as an example only. It contains all variables from all roles together and can be used as a template.

Per instruction, to start a new node you concatenate `all.network` that contains network-wide settings (including branch names) with role-specific `$role.example` which contains other options to get a complete `all` file.
