### ISSUE TITLE
(Feature) Playbook for archiving

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/deployment-playbooks#42]
The role should allow having archiving for
- validator
- bootnode

At the moment, archiving node on kovan/mainent runs with parameters
```
RUST_BACKTRACE=1 parity --pruning=archive --fat-db on --cache-size-db 12000 --min-peers 5 --max-peers 10 --snapshot-peers 500 --pruning-history 1200 --no-ui --no-dapps --auto-update=all --no-discovery --allow-ips=public --no-periodic-snapshot
```
we should use parameters

**Comment by phahulin** [comment]
Probably better to add an option to existing validator and bootnode roles `archiving: true/false` that would add these parameters to node.toml. To be done after https://github.com/poanetwork/deployment-playbooks/issues/45
