### ISSUE TITLE
(Feature) Add a prefix of network to security groups in AWS

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/deployment-playbooks#43]
Problem: Now we have the same security group for different networks. While tested `Sokol` I updated a security group and it affected `Core`. 😳
Solution: Add a prefix to security group, e.g. `core-` and `sokol-`

**Comment by phahulin** [comment]
I also suggest adding github account name:
```
{{ MAIN_REPO_FETCH }}-{{ GENESIS_BRANCH }}-{{ role }}-security
```
e.g. `poanetwork-core-moc-security`.

**Comment by phahulin** [comment]
Done.
