### ISSUE TITLE
Please consider supporting interactive auth for playbooks deployments

### ISSUE THREAD

**Issue by micwebnet** [poanetwork/deployment-playbooks#44]
If the SSH keys are password protected, ansible-playbook fails with

TASK [hf-spec-change : Shutdown poa-netstats service] *****************************************************************************
fatal: [52.191.165.235]: FAILED! => {"changed": false, "msg": "Unable to stop service poa-netstats: Failed to stop poa-netstats.service: Interactive authentication required.\nSee system logs and 'systemctl status poa-netstats.service' for details.\n"}
        to retry, use: --limit @/home/mm/poa-devops/site.retry

The workaround is to use non-password-protected ssh keys, but that's a security vulnerability if the control system is compromised. Suggest looking into allowing interactive auth during deployment.

Best,  MM

**Comment by phahulin** [comment]
Hi, to keep issues in order, I moved this one to https://github.com/poanetwork/poa-devops/issues/8 as it seems to deal with one of the scripts from that repository. Hope you don't mind.
