### ISSUE TITLE
Google as sole DNS provider 

### ISSUE THREAD

**Issue by jflowers1974** [poanetwork/deployment-playbooks#56]
Noticed that Google is being used for DNS services and only google (8.8.8.8 and 8.8.4.4) inside of /group_vars/all.  Although I do this myself, perhaps add another public DNS services provider...just in case google is unreachable? (Granted, if google's unreachable - we should probably be ducking and covering.)

![screen shot 2018-01-23 at 4 20 05 pm](https://user-images.githubusercontent.com/4926929/35307777-4d5a527c-0059-11e8-8649-b920ceefc46c.png)

**Comment by igorbarinov** [comment]
Good catch Jeff. What do you recommend?

Also we have ntp servers from one provider

**Comment by igorbarinov** [comment]
@phahulin 
let's add options
- Verisign https://www.verisign.com/en_GB/security-services/public-dns/index.xhtml
- Yandex https://dns.yandex.com/

**Comment by phahulin** [comment]
Turns out none of them are actually used, aws loads its own configuration
```
# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search ec2.internal
```
Can be overwritten following this instruction https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/
Will be implementing it in the playbook.

**Comment by VitalyZnachenok** [comment]
Hello, the variables now not used, we don't change resolve.conf, leave the by default.

**Comment by phahulin** [comment]
These settings were not really used. NTP and DNS server (at least in case of AWS) are set by the hosting platform, so either they should be changed on hoster's side or default values should be used.
