### ISSUE TITLE
Upgrade SOKOL to parity 1.9.2+

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#63]
Things to prepare:
- [x] playbook:
    * stop parity
    * backup current binary
    * backup current parity_data
    * backup current node.toml
    * download new binary
    * if bootnode - replace `threads` with `processing_threads` in node.toml
    * `parity db kill` ? resync ?
    * restart parity
    * restart netstats if it exists

Things to do:
- [x] update url of parity binary in https://github.com/poanetwork/deployment-playbooks/blob/master/group_vars/all.network#L25 to `https://d1h4xl4cr1h0mo.cloudfront.net/v1.9.2/x86_64-unknown-linux-gnu/parity`
- [x] update sha256 checksum to `3604a030388cd2c22ebe687787413522106c697610426e09b3c5da4fe70bbd33`
- [x] run playbook on bootnodes (except orchestrator)
- [x] run playbook on explorer
- [x] run playbook on moc
- [x] run playbook on validators' nodes

**Comment by phahulin** [comment]
Update instructions and new playbook https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

Not sure if we should do `db kill` to cause a resync. As I understand they've upgraded rocks db to a newer version and I saw some issues about 1.9.x where the recommended solution was to resync, so it's probably worth it. But upgrade worked for a test node without resync.
Anyway, now sokol-bootnode-archive is resyncing.

**Comment by phahulin** [comment]
Nodes to be updated on SOKOL:

- [ ] Bootnode-Orchestrator-1 *
- [ ] Bootnode-Orchestrator-2 *
- [ ] Bootnode-Orchestrator-3 *
- [ ] Stephen Arsenault
- [ ] Lillian Chan
- [ ] Master of Ceremony
- [ ] Roman Storm
- [ ] Bootnode-Traces
- [ ] Marat Pekker
- [ ] Rocco Federico Mancini
- [ ] Sokol Walter Karshat
- [ ] John H. LeGassic
- [ ] Bootnode
- [ ] Melanie Marsollier
- [ ] Sherina Hsuan Yang
- [ ] Henry Vishnevsky
- [ ] MM Azure EastUS Bootnode
- [ ] John D. Storey
- [ ] Jim O'Regan SOKOL Validator Chicago A
- [ ] Sokol Bootnode Toronto A
- [ ] Bootnode-HB
- [ ] Jeff Flowers (Val)
- [ ] Jeff Flowers
- [ ] Michael Milirud
- [ ] Jim O'Regan SOKOL Validator Chicago B
- [X] Bootnode-Archive

* - later, when corresponding version with whisper fixes is ready.

**Comment by rstormsf** [comment]
- [x] Roman
- [x] Marat
- [x] Henry

**Comment by elillian** [comment]
Just in case someone else has this problem. If you have more hosts files in your computer (for CORE and SOKOL), your computer may pull the file from other files. So, something that helped me immensely is pulling the file into the ansible line in the terminal. That way the terminal only pulls from the file you want it to use. Hope this helps someone too!

**Comment by phahulin** [comment]
@rstormsf all validators are on 1.9.2 now, could you please check consensus on sokol? maybe add some test validator, check that he appears in the validators list and then remove him?

**Comment by phahulin** [comment]
Few other notes on 1.9 vs 1.8:

1. now by default all `Host` headers are blacklisted, need to enable cors on public rpc nodes:
add `cors = ["all"]` to `[rpc]` section of node.toml otherwise cannot connect via MEW
2. exporting blocks (for backup) via `parity export blocks` is very slow, doesn't complete in an hour

Still doing some tests...

**Comment by phahulin** [comment]
Point 2. solved by one-time resync of the node.

**Comment by rstormsf** [comment]
@phahulin update:
I added new validator on sokol:
https://sokol-explorer.poa.network/account/0x8527153b9a747adce9fdf4274afe39211f15e0d3
https://sokol-explorer.poa.network/block/1145520

I was able to mine 2 blocks.
I'm going to remove this validator in 2 days

**Comment by rstormsf** [comment]
Update: succesfully removed validator. We should now proceed to update CORE to 1.9.2

**Comment by phahulin** [comment]
https://github.com/poanetwork/deployment-playbooks/issues/85
