### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#75]
Running virtual machine in the cloud just to test the change in the playbook is time consuming.

Better way is to test changes locally before applying them to `master` branch. There are two possible ways of doing this:

1. `vagrant` with `VirtualBox` & `Ansible` provisioners
2. `vagrant` with `Docker` & `Ansible` provisioners

Both options use Ubuntu images similar to those used in the cloud.

The second option is faster and require less resources.

Does this project use some kind of local testing already?

The workflow will look like:

1. Make a change to a playbook
2. `vagrant up` runs Docker container and applies playbook to this container
3. Check the result (manually for now, run integration tests in the future)
4. `vagrant down` tears down the container
5. Commit the change (`pre-commit` hook runs linter and syntax checks)

**Comment by phahulin** [comment]
Unfortunately we don't have auto-tests yet for different node types, but at least automatic node setup in a container and running playbook would be great
