### ISSUE TITLE
Default variables

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#76]
Currently all the variables are in the `group_vars/all` file.

1. [some variables][1] are not intended to be modified by the user
2. [some variables][2] may assume reasonable defaults

The first type of vars should be moved to the role level `vars` folder and the second to the `default` folder.

Variables on playbook level will be specific to the environment (`sokol` or `core`) and contain only required ones. That way it will be easier for the user to configure the deployment.

[1]: https://github.com/poanetwork/deployment-playbooks/blob/master/group_vars/all.example#L54-L56
[2]: https://github.com/poanetwork/deployment-playbooks/blob/master/group_vars/all.example#L95-L97

**Comment by phahulin** [comment]
I'd say there are 3 "levels" of variables:
1. network-wide - applies to all roles on a network, and are not intended to be modified by the user
2. role-specific - should assume reasonable defaults, but may be modified by the user
3. instance-specific - must be provided by the user (node name, keys, etc)

so `1` goes to `group_vars/sokol` or `group_vars/core` (if we agree on https://github.com/poanetwork/deployment-playbooks/issues/74)
`2` goes to `roles/xxx/default/main.yml`
`3` goes to `roles/xxx/vars/main.yml` - this one is empty and not managed by version control (added to `.gitignore`). Also, this is _the_ file that user modifies before running playbook

is that correct?
