### ISSUE TITLE
groups based on environment

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#77]
As a possible solution to #74 one may create two host groups in the inventory - `sokol` and `core`. Then add `sokol`-related variables to the `group_vars/sokol` file and `core`-related variables to the `group_vars/core` file.

Variables will live in a single branch and may be applied based on what deployment group hosts belong to. That makes possible maintaining both `sokol` and `core` deployments from a single playbook.

`group_vars/all` should be renamed to `group_vars/poa` which is applied to the `poa` group. `poa` group includes `sokol` and `core` as children.

**Comment by ArseniiPetrovich** [comment]
According to #74, we have decided to leave the current scheme with separation of branches.
