### ISSUE TITLE
Use Ansible-lint

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#78]
I am working on PR that will update playbooks to pass [Ansible-lint][1]. Linter checks the code against set of rules and generates errors in case of their violation.

I would suggest running linter as a `pre-commit` hook so each commit is validated.

Also run `ansible-playbook --syntax-check` to verify syntax and show deprecation warnings.

[1]: https://github.com/willthames/ansible-lint

**Comment by phahulin** [comment]
This would be a great PR
