### ISSUE TITLE
Dependent roles

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#80]
Current playbooks look like this

```
roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - validator
    - validator-access
```

What they should look like is this

```
roles:
  - validator
```

Only a single role that defines node type.

If one wants to co-locate two roles on a single node it is possible and clear:

```
roles:
  - validator
  - explorer
```

To achieve this use [Ansible role dependencies][1]

[1]: http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-dependencies

**Comment by phahulin** [comment]
There is no need to co-locate two roles on a single node, at least we can assume that if someone wants to do that, that's his own headache :)

so if playbook looks like
```
roles:
  - validator
```
what will `validator` role look like?

**Comment by lexsys27** [comment]
The same as it looks now except `meta` folder

`roles/validator/meta/main.yml`:

```
---
dependencies:
  - { role: usermanager, username: "validator" }
  - { role: nodejs, version: "XXX" }
  - { role: poa-logrotate }
```

Now `validator` role knows what Ansible must run before applying its tasks. That siplifies refactoring and configuration. If one decides to add `ntp` role to the validator they don't need to update their playbooks - just pull changes from GitHub and run playbook.
