### ISSUE TITLE
Update CORE to 1.9.2

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#85]
**Update instructions**: https://github.com/poanetwork/poa-devops/blob/master/docs/Update-parity-version.md

---

- [X] Migration playbook (https://github.com/poanetwork/poa-devops/blob/master/roles/upd-parity-version/tasks/main.yml):
    - [X] add `cors` section for bootnodes

- [x] Update nodes (I round - less critical nodes):
    - [x] Bootnode-Archive
    - [x] Bootnode-Traces
    - [x] Explorer

- [x] Update defaults in deployment playbooks repository (https://github.com/poanetwork/deployment-playbooks/pull/86):
    - [x] change default parity bin url to `https://d1h4xl4cr1h0mo.cloudfront.net/v1.9.2/x86_64-unknown-linux-gnu/parity`, checksum to `3604a030388cd2c22ebe687787413522106c697610426e09b3c5da4fe70bbd33`
    https://github.com/poanetwork/deployment-playbooks/blob/core/group_vars/all.network
    https://github.com/poanetwork/deployment-playbooks/blob/core/group_vars/all.example
    - [x] include the following commits from sokol upgrade:
    https://github.com/poanetwork/deployment-playbooks/commit/05b81aa09102e42cb3ddb7bdbc78dc181be442f8
    https://github.com/poanetwork/deployment-playbooks/commit/16096823e6c3a321154215948a23d12abbbeb844

- [x] Update nodes (II round - public rpc nodes and MoC):
    - [x] Bootnode A
    - [x] Bootnode B
    - [x] Bootnode C
    - [x] Bootnode D
    - [x] Bootnode MoC OVH
    - [x] Master of Ceremony

- [x] Update nodes (III round - part of validators)
    - [x] Jeff Flowers
    - [x] Jim O'Regan
    - [x] John H LeGassic
    - [x] Roman Storm

- [x] Notify BINANCE?

- [x] Update nodes (IV round - other bootnodes and validators):
    - [x] Bootnode Atlanta A
    - [x] Bootnode Azure Brazil A
    - [x] Bootnode Chicago A
    - [x] Bootnode Chicago B
    - [x] Bootnode Chicago C
    - [x] Bootnode Dallas A
    - [x] Bootnode Frankfurt
    - [x] Bootnode Santa Clara
    - [ ] ~Bootnode_Paris~
    - [x] Bootnode_YTI
    - [x] Alex Emelyanov
    - [x] John D. Storey
    - [x] Lillian Chan
    - [x] Melanie Marsollier
    - [x] Michael Milirud
    - [x] Rocco Federico Mancini
    - [x] Sherina Hsuan Yang
    - [x] Stephen Arsenault
    - [x] Sviataslau Vishneuski

- [x] Update nodes (V round - backup)
    - [x] Bootnode-HB

**Comment by 6proof** [comment]
Update nodes III round - part of validators - Jim O'Regan Validator node updated Parity 1.9.2 03/13/2018
Update nodes IV round - other bootnodes and validators - POA Core Bootnode Chicago A, Bootnode Chicago B, Bootnode Chicago C all updated to Parity 1.9.2  03/13/2018

**Comment by banteg** [comment]
Updated.
- [x] Bootnode Frankfurt

**Comment by youtweakit** [comment]
Bootnode_YTI updated

**Comment by 6proof** [comment]
Update nodes (III round - part of validators) - John H LeGassic and Jeff Flowers nodes updated 03/14/2018

**Comment by 6proof** [comment]
Update nodes Round III completed - can now notify Binance per outline.

**Comment by igorbarinov** [comment]
@6proof it's not a HF, it's not mandatory to notify. But ty for mentioning

**Comment by 6proof** [comment]
Thanks for the info Igor.  The notification was next in line and wasn't sure if the Github post was necessary to trigger an update.  Thanks again!

**Comment by hashguide** [comment]
- [ ] Bootnode Atlanta A
- [ ] Bootnode Dallas A
- [ ] Stephen Arsenault 

All updated and verified!

**Comment by RoccoFMancini** [comment]
My validator node is updated and verified.

**Comment by shkron** [comment]
Successfully updated

**Comment by henryvishnevsky** [comment]
Successfully upgraded Sviataslau Vishneuski validator node to version Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0

**Comment by micwebnet** [comment]
Successfully upgraded Michael Milirud validator node to Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0

**Comment by phahulin** [comment]
Checked Melanie's node

**Comment by phahulin** [comment]
All done
