### ISSUE TITLE
Unused (?) variables

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#88]
I can't find the usage of several variables defined in the `all.network` file. Could you please describe their purpose and where are they used?

```
snmp_syslocation: "USA"
snmp_ipsubnet:    "172.16.0.0/16"

nameservers:
  - "8.8.8.8"
  - "8.8.4.4"

ntpservers:
  - "server 0.us.pool.ntp.org"
  - "server 1.us.pool.ntp.org"
  - "server 2.us.pool.ntp.org"
  - "server 3.us.pool.ntp.org"
```

https://github.com/poanetwork/deployment-playbooks/blob/master/group_vars/all.network#L7-L18

**Comment by phahulin** [comment]
Yes, they are unused we considered deleting them.
By the way, maybe we could use your help here :) Do you think it's worth adding custom name servers and ntp servers in a playbook? Hosting providers like aws configure hosts to use their own servers, so maybe it's redundant? on the other hand, it look more fail-safe

**Comment by lexsys27** [comment]
Let's think. What scenario may require using servers different then supplied by hosting provider?

From reliability point of view the reliability of the whole providers infrastructure is nearly the same. So the is no value using Google DNS with 100% if EC2 vm is down.

From security point of view network protocols must not rely on a global clock or assume no naming conflicts. It is the idea of truly distributed system.

I would suggest to use the simplest way, delete these variables and use provider-specific defaults.
