### ISSUE TITLE
Local tests do no stop on error

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#93]
If machine fails to start during `make test` the tests show the error and then try to start the next machine.

The desired behavior is to fail on the first error.

The possible solution is

```
- vagrant up $$i || exit 1; \
+ vagrant up $$i; \
```

**Comment by phahulin** [comment]
@VladimirNovgorodov can this issue be closed after your PR is merged?

**Comment by ArseniiPetrovich** [comment]
@phahulin 
Yes, we can close this now.
