### ISSUE TITLE
Default variables on the role level

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#95]
Some variables may be moved to the role level and set up with reasonable defaults.

Variables that control access to the node:

```
allow_validator_ssh: true
allow_validator_p2p: true
```

Play variables:

```
nginx_headers: "on"
PROXY_PORT: "8545"
username: "bootnode"
users:
  - name: "bootnode"
home: "/home/bootnode"
```

Proposed structure is:

```
roles
|-bootnode
  |-defaults
    |-main.yml
```

**Comment by phahulin** [comment]
Those in `group_vars/` overwrite them (if set), correct?

**Comment by lexsys27** [comment]
Correct.

User may overwrite these variables with `group_vars`.

Variables that should not modified by the user should go to the `/vars` folder.
