### ISSUE TITLE
Refactor package list in preconf role

### ISSUE THREAD

**Issue by lexsys27** [poanetwork/deployment-playbooks#98]
At this moment list of packages that this role installs looks like this:

```
    - bc
    - haveged
    - rsync
    - iotop
    - dstat
    - sysstat
    - htop
    - lbzip2
    - pigz
    - unzip
    - zip
    - mtr
    - tcpdump
    - openssh-client
    - sudo
    - mc
    - net-tools
    - screen
    - git
    - cloud-utils
    - build-essential
    - nload
```

They fall into different categories but it is impossible to tell what is the exact purpose of each package.

*Sysadmin tools* `mtr` and `tcpdump` are typical examples. Operator uses these packages to troubleshoot issues on the node. If drop these packages node is still operational.

*POA Components dependencies* If drop these packages some of poa components will stop working. When poa component stops dependency on this packet it should be removed from the system.

*Ansible modules dependencies*. Ansible modules depend on these packages to do their tasks. If the module is not needed then this package should not be installed.

The proposal:

1. Move *ansible modules dependencies* to the role level where they are used.
2. Move *POA Components dependencies* to the role that installs these components.
3. Refactor *Sysadmin tools* into a separate role that user may choose to install optionally.
4. Install no packages in the `preconf` role

**Comment by Ykisialiou** [comment]
Looks like Sysadmin tools are:
   - rsync
    - iotop
    - dstat
    - htop
    - sysstat
    - tcpdump
    - net-tools
    - mc
    - cloud-utils
    - mtr
    - nload
    - screen
But I'm not sure about network components dependencies
    - bc
    - haveged
looks like smth related. 
And probably 
    - lbzip2
    - pigz
    - unzip
    - zip
are also necessary for some POA components. 
@phahulin Probably you can clarify? If no, I'll investigate in our sandbox.

**Comment by Ykisialiou** [comment]
@phahulin  I see. And maybe you can provide the info, which exact packages use haveged? Or should we install it everywhere?
If so, looks like the expected result will be to have haveged, git, and build-essentials at `preconf` role, to avoid writing the same code many times. And all other packages in `debug-tools` optional role, which is used by default.

**Comment by phahulin** [comment]
@Ykisialiou `haveged` is started as a service by itself when it's installed. It improves random number generator. Other packages don't use it. So it just needs to be installed

**Comment by ArseniiPetrovich** [comment]
Closing because of #127
